# -*- coding: utf-8 -*-
"""funzioni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCOvmNXy0AJM58H7p-Ns1JyAwmQHyIkR
"""

import random
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from config import *


def dimensione_azienda(tipo_azienda):
  nr_mucche_latte = random.randint(200,800)
  nr_mucche_carne = random.randint(100,300)
  ettari = random.randint(50,150)

  # capacità di raccolta del fieno: supponiamo che l'azienda intensiva abbia macchinari più potenti
  if tipo_azienda == "sostenibile":
    capacita_raccolta = random.randint(800, 1200) #kg/gg
  else:
    capacita_raccolta = random.randint(1500, 2500) #kg/gg

  return {"nr_mucche_latte" : nr_mucche_latte ,
          "nr_mucche_carne" : nr_mucche_carne ,
          "ettari" : ettari,
          "capacita_raccolta": capacita_raccolta}


def produzione_latte(nr_mucche, resa_giornaliera, giorni_simulazione):
    litri_al_giorno = nr_mucche * resa_giornaliera
    totale = litri_al_giorno * giorni_simulazione
    return totale


def produzione_carne(nr_mucche, gg_ingrasso, giorni_simulazione,
                     peso_iniziale=200, peso_finale=600):
    kg_per_capo = peso_finale - peso_iniziale
    cicli = giorni_simulazione / gg_ingrasso
    capi_completati = nr_mucche * cicli
    kg_totali = capi_completati * kg_per_capo
    return round(kg_totali, 2)


def produzione_fieno(nr_ettari, resa, giorni_simulazione):
    kg_fieno_prodotto = nr_ettari * resa * (giorni_simulazione / 365)
    return kg_fieno_prodotto


def calcolo_autosufficienza_mangime(kg_fieno_prodotto, nr_mucche_latte,
                                    consumo_fieno_per_mucca_latte,
                                    nr_mucche_carne, consumo_fieno_per_mucca_carne,
                                    giorni_simulazione):
    fabbisogno_latte = nr_mucche_latte * consumo_fieno_per_mucca_latte * giorni_simulazione
    fabbisogno_carne = nr_mucche_carne * consumo_fieno_per_mucca_carne * giorni_simulazione
    fabbisogno_totale = fabbisogno_latte + fabbisogno_carne
    surplus_deficit = kg_fieno_prodotto - fabbisogno_totale
    return fabbisogno_totale, surplus_deficit


def costo_azienda(nr_mucche_totali, nr_ettari, params, giorni_simulazione):
    costo_acq_animali = (nr_mucche_totali
                         * params["acqua_animali_giornaliera_media_litri"] / 1000
                         * giorni_simulazione
                         * costo_acqua)

    costo_acq_campi = (nr_ettari
                       * params["acqua_irrigazione_ettaro_m3_anno"]
                       * (giorni_simulazione / 365)
                       * costo_acqua)

    costo_fert = (nr_ettari
                  * params["fertilizzanti_ettaro_kg_anno"]
                  * (giorni_simulazione / 365)
                  * costo_fertilizzante)

    return round(costo_acq_animali + costo_acq_campi + costo_fert, 2)


def tempo_produzione(nr_mucche_latte, resa_giornaliera_latte,
                     gg_ingrasso,
                     nr_ettari, resa_ettaro_fieno, capacita_raccolta_giornaliera_kg):

    prod_latte_litri = produzione_latte(nr_mucche_latte, resa_giornaliera_latte, 365)
    produzione_giornaliera_latte = nr_mucche_latte * resa_giornaliera_latte
    gg_latte = prod_latte_litri / produzione_giornaliera_latte

    gg_carne = gg_ingrasso

    kg_fieno_totale = nr_ettari * resa_ettaro_fieno
    gg_fieno = kg_fieno_totale / capacita_raccolta_giornaliera_kg

    return {
        "gg_per_target_latte": round(gg_latte, 1),
        "gg_ciclo_carne"     : round(gg_carne, 1),
        "gg_raccolta_fieno"  : round(gg_fieno, 1),
        "gg_totale_lotto"    : round(max(gg_latte, gg_carne, gg_fieno), 1)
    }


def confronto(r1, r2):
    print(f"\n{'='*62}")
    print(f"  CONFRONTO: {r1['tipo']} vs {r2['tipo']}")
    print(f"{'='*62}")

    print(f"\n{'Parametri input':<30} {r1['tipo']:>15} {r2['tipo']:>15}")
    print(f"{'-'*62}")
    print(f"{'Mucche da latte':<30} {r1['nr_mucche_latte']:>15} {r2['nr_mucche_latte']:>15}")
    print(f"{'Mucche da carne':<30} {r1['nr_mucche_carne']:>15} {r2['nr_mucche_carne']:>15}")
    print(f"{'Ettari coltivati':<30} {r1['nr_ettari']:>15} {r2['nr_ettari']:>15}")

    print(f"\n{'Produzioni':<30} {r1['tipo']:>15} {r2['tipo']:>15}")
    print(f"{'-'*62}")
    print(f"{'Latte prodotto (L)':<30} {r1['litri_latte']:>15.2f} {r2['litri_latte']:>15.2f}")
    print(f"{'Carne prodotta (kg)':<30} {r1['kg_carne']:>15.2f} {r2['kg_carne']:>15.2f}")
    print(f"{'Fieno prodotto (kg)':<30} {r1['kg_fieno']:>15.2f} {r2['kg_fieno']:>15.2f}")

    print(f"\n{'Gestione mangime':<30} {r1['tipo']:>15} {r2['tipo']:>15}")
    print(f"{'-'*62}")
    print(f"{'Fabbisogno fieno (kg)':<30} {r1['fabbisogno_fieno']:>15.2f} {r2['fabbisogno_fieno']:>15.2f}")
    print(f"{'Surplus/deficit (kg)':<30} {r1['surplus_deficit']:>15.2f} {r2['surplus_deficit']:>15.2f}")

    print(f"\n{'Costi':<30} {r1['tipo']:>15} {r2['tipo']:>15}")
    print(f"{'-'*62}")
    print(f"{'Costo totale (euro)':<30} {r1['costo_totale']:>15.2f} {r2['costo_totale']:>15.2f}")

    print(f"\n{'Tempi di produzione (gg)':<30} {r1['tipo']:>15} {r2['tipo']:>15}")
    print(f"{'-'*62}")
    print(f"{'Giorni target latte':<30} {r1['tempi']['gg_per_target_latte']:>15.1f} {r2['tempi']['gg_per_target_latte']:>15.1f}")
    print(f"{'Giorni ciclo carne':<30} {r1['tempi']['gg_ciclo_carne']:>15.1f} {r2['tempi']['gg_ciclo_carne']:>15.1f}")
    print(f"{'Giorni raccolta fieno':<30} {r1['tempi']['gg_raccolta_fieno']:>15.1f} {r2['tempi']['gg_raccolta_fieno']:>15.1f}")
    print(f"{'Tempo totale lotto':<30} {r1['tempi']['gg_totale_lotto']:>15.1f} {r2['tempi']['gg_totale_lotto']:>15.1f}")

    print(f"\n{'='*62}\n")


def genera_grafici_confronto(r1, r2):
    labels = [r1['tipo'], r2['tipo']]

    produzioni_latte = [r1['litri_latte'], r2['litri_latte']]
    costi_totali = [r1['costo_totale'], r2['costo_totale']]
    tempi_lotto = [r1['tempi']['gg_totale_lotto'], r2['tempi']['gg_totale_lotto']]

    fig, ax = plt.subplots(1, 3, figsize=(18, 5))
    fig.suptitle('Analisi Comparativa Processi Produttivi', fontsize=16)

    ax[0].bar(labels, produzioni_latte, color=['#4CAF50', '#F44336'])
    ax[0].set_title('Volume Latte Prodotto (L)')
    ax[0].set_ylabel('Litri')

    ax[1].bar(labels, costi_totali, color=['#81C784', '#E57373'])
    ax[1].set_title('Costi Operativi Totali (€)')
    ax[1].set_ylabel('Euro')

    ax[2].bar(labels, tempi_lotto, color=['#2E7D32', '#C62828'])
    ax[2].set_title('Tempo Completamento Lotto (GG)')
    ax[2].set_ylabel('Giorni')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()


def salva_report_pdf(r1, r2, nome_file="report_azienda.pdf"):

    c = canvas.Canvas(nome_file, pagesize=A4)
    larghezza, altezza = A4
    y = altezza - 50

    def scrivi(testo, dimensione=11, grassetto=False, spazio=18):
        nonlocal y
        if grassetto:
            c.setFont("Helvetica-Bold", dimensione)
        else:
            c.setFont("Helvetica", dimensione)
        c.drawString(50, y, testo)
        y -= spazio

    def scrivi_riga(etichetta, val1, val2):
        nonlocal y
        c.setFont("Helvetica", 10)
        c.drawString(50,  y, etichetta)
        c.drawString(350, y, str(val1))
        c.drawString(470, y, str(val2))
        y -= 16

    def linea():
        nonlocal y
        c.line(50, y, larghezza - 50, y)
        y -= 10

    scrivi("REPORT DI SIMULAZIONE - AZIENDA ZOOTECNICA", dimensione=14, grassetto=True, spazio=10)
    scrivi(f"Durata simulazione: {gg_simulazione} giorni", dimensione=10, spazio=6)
    linea()

    scrivi_riga("", r1["tipo"], r2["tipo"])
    linea()

    scrivi("Parametri input", grassetto=True, spazio=14)
    scrivi_riga("Mucche da latte",  r1["nr_mucche_latte"], r2["nr_mucche_latte"])
    scrivi_riga("Mucche da carne",  r1["nr_mucche_carne"], r2["nr_mucche_carne"])
    scrivi_riga("Ettari coltivati", r1["nr_ettari"],       r2["nr_ettari"])
    y -= 6
    linea()

    scrivi("Produzioni", grassetto=True, spazio=14)
    scrivi_riga("Latte prodotto (L)",  f"{r1['litri_latte']:.2f}",  f"{r2['litri_latte']:.2f}")
    scrivi_riga("Carne prodotta (kg)", f"{r1['kg_carne']:.2f}",     f"{r2['kg_carne']:.2f}")
    scrivi_riga("Fieno prodotto (kg)", f"{r1['kg_fieno']:.2f}",     f"{r2['kg_fieno']:.2f}")
    y -= 6
    linea()

    scrivi("Gestione mangime", grassetto=True, spazio=14)
    scrivi_riga("Fabbisogno fieno (kg)", f"{r1['fabbisogno_fieno']:.2f}", f"{r2['fabbisogno_fieno']:.2f}")
    scrivi_riga("Surplus/deficit (kg)",  f"{r1['surplus_deficit']:.2f}",  f"{r2['surplus_deficit']:.2f}")
    y -= 6
    linea()

    scrivi("Costi", grassetto=True, spazio=14)
    scrivi_riga("Costo totale (euro)", f"{r1['costo_totale']:.2f}", f"{r2['costo_totale']:.2f}")
    y -= 6
    linea()

    scrivi("Tempi di produzione (giorni)", grassetto=True, spazio=14)
    scrivi_riga("Giorni target latte",   f"{r1['tempi']['gg_per_target_latte']:.1f}", f"{r2['tempi']['gg_per_target_latte']:.1f}")
    scrivi_riga("Giorni ciclo carne",    f"{r1['tempi']['gg_ciclo_carne']:.1f}",      f"{r2['tempi']['gg_ciclo_carne']:.1f}")
    scrivi_riga("Giorni raccolta fieno", f"{r1['tempi']['gg_raccolta_fieno']:.1f}",   f"{r2['tempi']['gg_raccolta_fieno']:.1f}")
    scrivi_riga("Tempo totale lotto",    f"{r1['tempi']['gg_totale_lotto']:.1f}",     f"{r2['tempi']['gg_totale_lotto']:.1f}")
    y -= 6
    linea()

    c.save()
    print(f"Report salvato come '{nome_file}'")
