# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XI-n3a6WEYmu5vWb0JVLS3jj57oAhmA2
"""

from config import *
from funzioni import *

azienda_sostenibile_dims = dimensione_azienda("sostenibile")
nr_mucche_latte_s = azienda_sostenibile_dims["nr_mucche_latte"]
nr_mucche_carne_s = azienda_sostenibile_dims["nr_mucche_carne"]
nr_ettari_s = azienda_sostenibile_dims["ettari"]
capacita_raccolta_s = azienda_sostenibile_dims["capacita_raccolta"]

azienda_intensiva_dims = dimensione_azienda("intensiva")
nr_mucche_latte_i = azienda_intensiva_dims["nr_mucche_latte"]
nr_mucche_carne_i = azienda_intensiva_dims["nr_mucche_carne"]
nr_ettari_i = azienda_intensiva_dims["ettari"]
capacita_raccolta_i = azienda_intensiva_dims["capacita_raccolta"]


report_sostenibile = {
    "tipo"           : "Sostenibile",
    "nr_mucche_latte": nr_mucche_latte_s,
    "nr_mucche_carne": nr_mucche_carne_s,
    "nr_ettari"      : nr_ettari_s,
    "litri_latte"    : produzione_latte(
                           nr_mucche_latte_s,
                           params_azienda_sostenibile["resa_giornaliera_latte_per_mucca"],
                           gg_simulazione),
    "kg_carne"       : produzione_carne(
                           nr_mucche_carne_s,
                           params_azienda_sostenibile["gg_ingrasso"],
                           gg_simulazione),
    "kg_fieno"       : produzione_fieno(
                           nr_ettari_s,
                           params_azienda_sostenibile["resa_ettaro_anno_fieno_kg"],
                           gg_simulazione),
    "costo_totale"   : costo_azienda(
                           nr_mucche_latte_s + nr_mucche_carne_s,
                           nr_ettari_s,
                           params_azienda_sostenibile,
                           gg_simulazione),
}

fabbisogno_s, surplus_s = calcolo_autosufficienza_mangime(
    report_sostenibile["kg_fieno"],
    nr_mucche_latte_s, fieno_mucca_latte_kg_giornaliero,
    nr_mucche_carne_s, fieno_mucca_carne_kg_giornaliero,
    gg_simulazione
)
report_sostenibile["fabbisogno_fieno"] = fabbisogno_s
report_sostenibile["surplus_deficit"]  = surplus_s
report_sostenibile["tempi"] = tempo_produzione(
    nr_mucche_latte_s,
    params_azienda_sostenibile["resa_giornaliera_latte_per_mucca"],
    params_azienda_sostenibile["gg_ingrasso"],
    nr_ettari_s,
    params_azienda_sostenibile["resa_ettaro_anno_fieno_kg"],
    capacita_raccolta_s
)

report_intensiva = {
    "tipo"           : "Intensiva",
    "nr_mucche_latte": nr_mucche_latte_i,
    "nr_mucche_carne": nr_mucche_carne_i,
    "nr_ettari"      : nr_ettari_i,
    "litri_latte"    : produzione_latte(
                           nr_mucche_latte_i,
                           params_azienda_intensiva["resa_giornaliera_latte_per_mucca"],
                           gg_simulazione),
    "kg_carne"       : produzione_carne(
                           nr_mucche_carne_i,
                           params_azienda_intensiva["gg_ingrasso"],
                           gg_simulazione),
    "kg_fieno"       : produzione_fieno(
                           nr_ettari_i,
                           params_azienda_intensiva["resa_ettaro_anno_fieno_kg"],
                           gg_simulazione),
    "costo_totale"   : costo_azienda(
                           nr_mucche_latte_i + nr_mucche_carne_i,
                           nr_ettari_i,
                           params_azienda_intensiva,
                           gg_simulazione),
}

fabbisogno_i, surplus_i = calcolo_autosufficienza_mangime(
    report_intensiva["kg_fieno"],
    nr_mucche_latte_i, fieno_mucca_latte_kg_giornaliero,
    nr_mucche_carne_i, fieno_mucca_carne_kg_giornaliero,
    gg_simulazione
)
report_intensiva["fabbisogno_fieno"] = fabbisogno_i
report_intensiva["surplus_deficit"]  = surplus_i
report_intensiva["tempi"] = tempo_produzione(
    nr_mucche_latte_i,
    params_azienda_intensiva["resa_giornaliera_latte_per_mucca"],
    params_azienda_intensiva["gg_ingrasso"],
    nr_ettari_i,
    params_azienda_intensiva["resa_ettaro_anno_fieno_kg"],
    capacita_raccolta_i
)


confronto(report_sostenibile, report_intensiva)
genera_grafici_confronto(report_sostenibile, report_intensiva)
salva_report_pdf(report_sostenibile, report_intensiva)